### ISSUE TITLE
Indicate ECC neighborhood status in sidebar

### ISSUE THREAD

**Issue by flibbertigibbet** [azavea/echo-locator#128]
Do not differentiate on the map between ECC and non-ECC neighborhoods, but in the sidebar summary and/or detail cards, display something extra for ECC neighborhoods.

Depends on #127.

**Comment by lederer** [comment]
Recommend implementing this as `<span>Expanded Choice Community</span>`, placed anywhere inside the sidebar card. I will follow up with styling and positioning it (and possibly switching to a symbol instead of text).
