### ISSUE TITLE
Change Mapbox token

### ISSUE THREAD

**Issue by flibbertigibbet** [azavea/echo-locator#139]
Update in staging and production environment S3 configuration files, and in internal development configuration example file.

**Comment by flibbertigibbet** [comment]
Blocked pending updated token that works with our map layers.

**Comment by ansoncfit** [comment]
Will address with #141

**Comment by ansoncfit** [comment]
I used Mapbox's beta URL restriction, but did not include localhost.  Just removed the restriction, so token should work.

**Comment by flibbertigibbet** [comment]
The token works locally now, thanks @ansoncfit. The token has been updated on staging and production.
