### ISSUE TITLE
Toggle commuter rail

### ISSUE THREAD

**Issue by flibbertigibbet** [azavea/echo-locator#140]
Add to user profile option to include/exclude commuter rail in results; default to include. Add results bucket without commuter rail to app configuration.

Requires making results bucket dynamic based on user profile change.

**Comment by ansoncfit** [comment]
Nick requested we bundle commuter rail together with express bus.  So the result buckets would be the ones you already have for all modes, and these, which exclude commuter rail and express bus routes:

Peak: `5cb8ebc037ed813dbe29182e`
Off-Peak: `5cb8ebe437ed813dbe291830`

**Comment by flibbertigibbet** [comment]
I'm not finding those keys under the bucket at https://d2z7d5345ccuw9.cloudfront.net/, where the existing two results are. Could I have the full URLs, please?

**Comment by ansoncfit** [comment]
Hmm... any luck with these?

https://d2z7d5345ccuw9.cloudfront.net/5cb8ebc037ed813dbe29182e/request.json

https://d2z7d5345ccuw9.cloudfront.net/5cb8ebe437ed813dbe291830/request.json

**Comment by flibbertigibbet** [comment]
Thank you, those are accessible. Could you please add CORS for `localhost` access?
