### ISSUE TITLE
Update transit layer

### ISSUE THREAD

**Issue by flibbertigibbet** [azavea/echo-locator#141]
Update Mapbox label layer for new version with transit stops and bus routes labeled, when we get it.

**Comment by ansoncfit** [comment]
Planning to add transit stops soon.

**Comment by ansoncfit** [comment]
The Echolocator Transit style was just re-published with stops. Agreed with Nick not to label bus routes.

**Comment by flibbertigibbet** [comment]
@ansoncfit thank you! Do we need to update our layer references?

**Comment by ansoncfit** [comment]
Sorry @flibbertigibbet I forgot we were using the "Echolocator Labels" style.  I just added the stops (and hospitals at high zoom levels, addressing #130) to that layer (`...8kqxel`).

If you eventually want to have the transit lines/stops able to be toggled (e.g. to hide them when specific routes from Taui are showing), we can split the lines/stops out to a separate "Echolocator Transit" style (`...auqn81`, not sure if the full id was forwarded to you)

**Comment by flibbertigibbet** [comment]
Looks great, thanks!
