### ISSUE TITLE
Additional mouse in/out interactions on neighborhood bounds

### ISSUE THREAD

**Issue by flibbertigibbet** [azavea/echo-locator#161]
See #160.

### Search screen
 - When hovering a sidebar card, paint the corresponding polygon fill green.
 - When hovering a map poly that has a corresponding sidebar card, make it the active neighborhood (deactivate other neighborhoods; make its sidebar and map markers green; render its route)
 - When hovering a **routable** map poly that does not have a corresponding sidebar card, deactivate any active neighborhood (hide route, change marker to blue, remove green fill, etc).
    - Bonus point 1: Add a green marker to the hovered poly (only while hovered).
    - Bonus point 2: Render a route to that marker (only while hovered). Obviously skip this if non-trivial.
- When hovering a **non-routable** poly:
  - Do not activate it (do not paint it green, do not show a marker).
  - Cursor should remain `grab` rather than `pointer`. 
  - Clicking should do nothing.
  - Show a tooltip with the neighborhood name and "Cannot be reached by transit"

### Detail screen
 - The selected neighborhood's polygon should be filled green and its centroid (or route endpoint) should have a green marker.
 - When hovering a **routable** map poly other than the selected one, paint it green and show its name in a tooltip. Do not render its marker or route. Keep the selected neighborhood polygon green.
- When hovering a **non-routable** poly:
  - Do not activate it (do not paint it green, do not show a marker).
  - Cursor should remain `grab` rather than `pointer`. 
  - Clicking should do nothing.
  - Show a tooltip with the neighborhood name and "Cannot be reached by transit"

**Comment by flibbertigibbet** [comment]
@lederer regarding: "When hovering a non-routable poly: ... Cursor should remain grab rather than pointer."

Since [interactivity is on the map layer](https://leafletjs.com/reference-1.5.0.html#interactive-layer), not its features, changing the map cursor on a feature event isn't something Leaflet supports. It might be possible to achieve this by overriding the [map interactivity style](https://github.com/Leaflet/Leaflet/blob/master/dist/leaflet.css#L208) in a hover event listener, but it would be a fragile modification to Leaflet that might cause other issues.

**Comment by lederer** [comment]
VectorGrid apparently [supports both SVG and Canvas rendering](https://leaflet.github.io/Leaflet.VectorGrid/vectorgrid-api-docs.html#svg-vs-canvas). We're using Canvas, but if we're able to switch to SVG, we should be able to conditionally apply [classnames to individual SVG polygons](https://leafletjs.com/reference-1.5.0.html#path) via VectorGrid's `vectorTileLayerStyles` option. This should allow us to conditionally set the cursor via CSS.

Toward this end, I tried replacing `Leaflet.canvas.tile` with `Leaflet.SVG.tile` in [vector-grid.js#L20](https://github.com/azavea/echo-locator/blob/develop/taui/src/components/vector-grid.js#L20) but it just led to a bunch of `Uncaught TypeError: this.options.rendererFactory is not a function` errors that I couldn't resolve. So this might be a dead end, in which case so it goes. 

But if there's a simple enough solution to resolving those errors, and if there are no technical reasons to avoid SVGs in this project, then we should be able to solve the cursor problem.
