### ISSUE TITLE
Hide some school ranks in UI

### ISSUE THREAD

**Issue by flibbertigibbet** [azavea/echo-locator#179]
Based on an added data source column to indicate which neighborhoods should have their school rankings hidden in the UI (for those areas averaged due to school choice), do not show the school ranking value or quintile label in the neighborhood detail if marked to be hidden, but use the school ranking value when sorting.

**Comment by lederer** [comment]
For school choice neighborhoods, I believe the idea was to hide the graph, but show:

`Schools: <a>School Choice</a>`

… where the link goes to the cambridge/boston public schools website.
