### ISSUE TITLE
Clicking "Sign Out" on the map page directs to blank page

### ISSUE THREAD

**Issue by ddohler** [azavea/echo-locator#192]
I noticed this while testing #191, but it happens on staging too: If I click "Sign Out" on the map page, I get a blank page, and the URL is `/map`. There's a console error stating `TypeError: profile is null`. If I reload the page, I'm shown the signin screen, as expected.

**Comment by flibbertigibbet** [comment]
This is fixed in #185.

**Comment by ddohler** [comment]
Indeed it is / was!
