### ISSUE TITLE
Implement profile page

### ISSUE THREAD

**Issue by flibbertigibbet** [azavea/echo-locator#22]
Display account profile details fetched from S3 after account selected. Write settings back to S3 on user clicking 'Go' button.

![image](https://user-images.githubusercontent.com/960264/52225613-ce124080-2878-11e9-8d0a-2f8f92fec41b.png)

![image](https://user-images.githubusercontent.com/960264/52225985-c3a47680-2879-11e9-8d2f-4961f6dc2bc2.png)

Depends on #21.

**Comment by flibbertigibbet** [comment]
@lederer what should 'Cancel' do here?

**Comment by lederer** [comment]
> what should 'Cancel' do here?

If the user lands here from the "New Search" page, Cancel should return to that page (equivalent to clicking "New" in the global nav). 

If they land here after clicking Edit in the global nav of the search or detail page, then Cancel should abandon any edits to this form and return to the page they came from.
