### ISSUE TITLE
Multiple tooltips showing at once

### ISSUE THREAD

**Issue by lederer** [azavea/echo-locator#230]
Mousing along the sidebar causes multiple tooltips to render at once.

Ideal solution: Triggering a tooltip automatically hides any currently visible tooltips.

If that's not possible, we may be able to optimize the `delayHide` and `delayShow` values to minimize the likelihood of this happening.

<img width="652" alt="Screen Shot 2019-06-20 at 12 45 44 PM" src="https://user-images.githubusercontent.com/128699/59866377-6c4f0080-9359-11e9-98a6-360d7daddac0.png">

**Comment by lederer** [comment]
If the above solutions don’t work, we may need to eliminate links from tooltips so we can set the hide delay to ~0.

**Comment by flibbertigibbet** [comment]
`delayUpdate` is supposed to prevent that, but introduces a bug; after the delay, the tooltip jitters to a new location, ignoring the `effect` setting.

**Comment by lederer** [comment]
If we need to eliminate links, we could move them to the sidebar footer, since the links aren't dynamic.

**Comment by flibbertigibbet** [comment]
The source links are dynamic. For example, the source for violent crime rates in Boston differs from outside Boston zip codes.

**Comment by lederer** [comment]
True, but that example appears to be the only dynamism. The footer copy could be something like the following:

_Schools data via <a href="">MA DOE</a>. Boston public safety data via <a href="">Boston Police Department Incident Reports</a>. Additional public safety data via <a href="">FBI Uniform Crime Reporting</a>. Rental units data via <a href="">MAPC</a>._
