### ISSUE TITLE
Disable browser autofill for voucher number

### ISSUE THREAD

**Issue by flibbertigibbet** [azavea/echo-locator#271]
Do not auto-suggest voucher numbers on the voucher number text field in the search page (or login page, if used for client account login).

**Comment by ddohler** [comment]
https://developer.mozilla.org/en-US/docs/Web/Security/Securing_your_site/Turning_off_form_autocompletion

I've never used this so I don't know what the impact will be in practice, but it's easy enough that it seems worth trying. There is some consideration of login fields on the page as well.

**Comment by flibbertigibbet** [comment]
Thanks. The jQuery input field name scrambler is an interesting workaround.
