### ISSUE TITLE
Allow using either phone or email to register

### ISSUE THREAD

**Issue by flibbertigibbet** [azavea/echo-locator#277]
Instead of requiring an email address to register an account, allow Cognito users to sign up with either an email address or a phone number.

 - modify staging stack configuration to allow phone number account registration
 - update staging stack README to document configuration changes
 - regenerate staging stack with a new Cognito user pool
 - add phone number field to form for counselors to invite clients
 - add validation for the phone number field and check either phone or email submitted
 - modify client account creation function to accept and use phone number
 - recreate staging user accounts for new Cognito user pool

**Comment by ddohler** [comment]
Clients are now required to have an email address in order to register.
