### ISSUE TITLE
Redirect to login page after Cognito account deleted

### ISSUE THREAD

**Issue by flibbertigibbet** [azavea/echo-locator#291]
Follow up to #289.

In the uncommon situation that a client logs in who has no private profile on S3, but there is another profile on S3 with the client's voucher number, but assigned a different email address, the Cognito account gets deleted for the client who just logged in. At that point, their browser should redirect to login, but instead displays a blank page apart from the header bar.

**Comment by ddohler** [comment]
No longer relevant under Django-based login system.
