### ISSUE TITLE
Redirect to login if unauthenticated

### ISSUE THREAD

**Issue by flibbertigibbet** [azavea/echo-locator#299]
If the user clears their cookies with the site loaded and then attempts to interact with the site in a way that requires authentication without first refreshing the page, the site will not function as expected. If an interaction with S3 or Cognito fails due to missing or invalid authentication information, the site should redirect to the login page.

For example, if a counselor is on the account search page and clears cookies, then attempts a search, no result or error displays on the page, and the error "No current user" logs to console.

![image](https://user-images.githubusercontent.com/960264/72631102-c16be880-3921-11ea-8c5b-5375c1d47df9.png)

If the user reloads the page or attempts to navigate to another page after clearing cookies, the site does redirect to the login page as expected; this issue is on site interaction without page (re-)load.

**Comment by ddohler** [comment]
The new login system has resolved this issue.
