### ISSUE TITLE
Add demo subdomain for existing staging site

### ISSUE THREAD

**Issue by coalkettler** [azavea/echo-locator#349]
The existing staging site, at https://staging.echolocator.org/ , used to be our staging site, but is no longer connected to CI, and has diverged from the set of features that we plan to implement as part of this project. However, BHA wants to maintain the current state of https://staging.echolocator.org/ as a demonstration site, so we need to move it to a new location so that they can continue to use it for demos after we begin development.

Tasks:
- Create a new DNS record to allow users to access the content which is currently at staging.echolocator.org via the domain name demo.echosearch.org (not the change in root domain).
- Verify that site functionality remains the same when accessing the site via `staging.echolocator.org` and the new domain name. Credentials are available as `BHA ECHO Staging` in our password manager.

Notes:
- echosearch.org is managed via the same AWS account as echolocator.org , so I _think_ it should be about the same effort to add `demo.echosearch.org` as it would be to add `demo.echolocator.org`, and that's the client's preferred option, so we should start by trying that. If it turns out that it's hard to switch the root domain for some reason, then we should use `demo.echolocator.org` as a fall-back.

**Comment by stephwall** [comment]
They're fine with using demo.echolocator.org for the demonstration site.

**Comment by ddohler** [comment]
https://demo.echosearch.org/ is live and points to the same Cloudfront distribution that staging.echolocator.org currently does.
