### ISSUE TITLE
Change logo

### ISSUE THREAD

**Issue by ddohler** [azavea/echo-locator#353]
Switch to the new ECHO logo.

@stephwall I recall that BHA said they'd send us their logo files for us to choose the appropriate one, have they done that?

**Comment by stephwall** [comment]
Yes, they can be found in the project folder here: https://drive.google.com/file/d/1t-uBtqvjGrP6BwXq_SOrMjDjgq_MvYeH/view?usp=sharing

**Comment by lederer** [comment]
The login screen should use `echo_combined_logo_STACKED_fullcolor.svg`.
The main header should use `echo_combined_logo_fullcolor.svg`.
