### ISSUE TITLE
Add Spanish and Chinese translations and language switcher

### ISSUE THREAD

**Issue by ddohler** [azavea/echo-locator#355]
This exists on [the demo site](https://demo.echosearch.org) and our implementation should match the functionality there.

## Notes
- The functionality match doesn't need to be perfect. If you see easy opportunities for improvement, feel free to take them.
- Feel free to reuse as much, or as little, of the code on the `demo` branch as is helpful.

**Comment by natastro** [comment]
Hello! I'm happy to help with Spanish translations if needed.

**Comment by ddohler** [comment]
Hi @natastro -- thanks! I believe that someone has already done the translation work, but I greatly appreciate the offer!
