### ISSUE TITLE
Display apartment detail on markers

### ISSUE THREAD

**Issue by ddohler** [azavea/echo-locator#358]
The [demo site](https://echosearch.org) allows users to hover over a map marker in order to see detailed information about an apartment, including a listing photo, rental cost, and a link to further details. We should re-implement this functionality.

## Screenshots
<img width="606" alt="Screen Shot 2021-10-13 at 10 12 03 AM" src="https://user-images.githubusercontent.com/447977/137150245-8d3489d6-31b5-41c4-a520-711dff808d90.png">

## Notes
- @lederer The current popup-on-hover functionality is kind of frustrating to use because it recenters the map, so if you hover over a marker near the edge accidentally the map will move suddenly and unexpectedly. I think we could stop it from recentering while still displaying the popups on hover, or we could switch the popups to display only on a click but maintain the recentering behavior. Do you have any thoughts?
- We can reuse as much or as little of the code on the `demo` branch as is helpful when re-implementing this, and the popups do not need to match the demo site exactly.

**Comment by lederer** [comment]
Let's start with just disabling the re-centering behavior.

Typically, popup-on-hover is fine if the amount of content in the popup is small. This popup looks like it may be sizable enough to require a click. But… let's try out hover and see how it goes.
