### ISSUE TITLE
Design Pass

### ISSUE THREAD

**Issue by stephwall** [azavea/echo-locator#388]
Design pass for "Task 1 Priority Changes":

- [x] Logo update
- [x] Copy changes to profile page
- [ ] Signin error message text
- [x] Spanish and Chinese translations (buttons, text, layout implications)
- [x] BHA and Realtor.com unit map display (buttons, markers, popup, routing)
- [x] Listing routing (sidebar routing info, error message)

@ktohalloran and @rachelekm, please add things that I might have missed.

**Comment by ktohalloran** [comment]
Not sure if this is a design pass task or should be it's own issue, but there is code for a school meter, similar to how there are public safety and rental units meters with matching tooltips on each neighborhood list detail; however, one isn't appearing on the site.

**Comment by stephwall** [comment]
@ktohalloran, are you referring to how instead of a scale, it has a "School choice options" button? If so, that's because Boston public schools aren't strictly neighborhood-based, meaning you can go to any school in the district. For neighborhoods outside of Boston, the scale does appear.

**Comment by ktohalloran** [comment]
@stephwall yes, I am, thank you for clarifying that! Please disregard my comment.
