### ISSUE TITLE
Diagram authentication / user profile system

### ISSUE THREAD

**Issue by ddohler** [azavea/echo-locator#394]
We are going to replace the authentication and user profile features (currently powered by a combination of AWS Amplify, S3, Cognito, and Lambda functions) with equivalent functionality powered by Django. In order to do that, we need a map of how all those components fit together and what the various pieces do. This task is to create a visual and/or textual description of how the authentication and profile parts of the app work so that we can come up with a plan for migrating them to Django. This task does NOT include coming up with that plan -- the work here is primarily descriptive, though if you spot things that are obviously relevant for a Django migration, be sure to flag them.

Here are the components of that process that I currently know about and what they do; this is probably not an exhaustive list, and this is just my best understanding of what each component does -- it may be incorrect or incomplete:
- Cognito: Provides authentication services, password resets, invitation emails, etc. Also stores limited profile information in order to differentiate between staff users (who can access any profile) and voucher holders (who can't). Users can be managed via the AWS console.
- S3: Stores profile information in JSON files. We also store non-profile information here, but I believe those files are public so we should be able to continue using them.
- Lambda functions: These manipulate profile files on S3 in order to keep users from accessing each others' profiles. The initial way the profiles worked was that the voucher number was the only authentication token users had, and each voucher number was associated with a file on S3 (e.g. `s3://echo-locator-profiles/11111111`. But that would have allowed users to access each other's profiles by putting in someone else's voucher number, so now each user signs up with an email, which is linked to a voucher number during signup, and then they are given their own, private profile file (e.g. `s3://echo-locator-profiles/13405987101904810948`) when they log in. These Lambda functions are responsible for making all that happen. This is the area I know the least about, so this description may be off. Also, in staging, these Lambda functions were accidentally deleted and then not re-created correctly, so as far as I can tell they are not functional on staging.
- Amplify: Amplify handles providing access to AWS resources, such as Cognito, Lambda, and S3. It provides utility functions that allow us to interact with AWS resources. Since we will be replacing those AWS resources with Django API calls, I think we can assume that we won't need to use Amplify after migrating to Django, but we should identify the places where Amplify's functions are used and what they're doing. Amplify also provides a React component library that can integrate with AWS resources. The primary way in which we've used the React components is to set up the authentication flow; Amplify has pre-built login components for showing login and signup screens, and preventing users from viewing the rest of the app if they're not logged in. I think it's likely that all of the components associated with the login flow will need to be re-written from scratch, but we'll still need to document how the existing components integrate with the rest of the app.

**Comment by rachelekm** [comment]
@ktohalloran and I collaborated on this issue and organized the details of this authentication/user profile system into resources found in [this folder.](https://drive.google.com/drive/folders/1oA2b_KUvItY7Ecn9sWFQ6N1jFd7HgW_T?usp=sharing) Included are three diagrams illustrating where our application has major touch points with Amplify/AWS resources. There is also a written overview that acts as a narrative description of the authentication/user profile workflows and supplement to the diagrams. We recommend starting with the overview to provide the best context to use these resources.

**Comment by ddohler** [comment]
Great writeup and diagrams, these really help to make the whole assembly clearer and will serve as a guide for us to plan the Django migration. Thanks for putting in the effort to figure everything out and diagram it so clearly!
