### ISSUE TITLE
New translations needed

### ISSUE THREAD

**Issue by lederer** [azavea/echo-locator#398]
Update to this task: BHA will send us all the missing translations. This issue should cover installing any new translations that we receive, including translations related to the strings mentioned below, as well as any remaining strings related to #389 and #391 .

The following EN strings were changes in #397 and will need new ES and ZH strings:

- `NeighborhoodDetails.ApartmentsToggles`
  - Formerly `NeighborhoodDetails.Apartments`
  - "Show apartments from"
- `NeighborhoodDetails.ListingsFetchError`
  - "Could not fetch listings"
- `Systems.TripsEmpty`
  - "No routes found to that destination"

You should branch off of `release/2022-03-02` for this work and make the PR back to that same branch.

**Comment by ddohler** [comment]
See also #389

**Comment by ddohler** [comment]
We have some new translations, but they may not cover everything. Please consult @aaronxsu for any missing Chinese translations. We have some (non-native) Spanish language knowledge on the team so hopefully we can put those together based on existing translations, but we have other resources at the company if not (and BHA said their translators are willing to review, so taking our best guess and flagging it for them is also an option).
