### ISSUE TITLE
Set up CI to bundle and deploy the app with Mastarm

### ISSUE THREAD

**Issue by jeancochrane** [azavea/echo-locator#4]
Configure a CI pipeline to deploy the app using Mastarm, with deployment logic wrapped in an `infra` script.

Since this app is being developed in the open, we expect to use Travis for CI. If Travis proves an unacceptable choice, make a determination for a different build tool to use. Common alternatives include:
* Jenkins
* AWS CodeBuild

Depends #3.
Depends on #7.

**Comment by flibbertigibbet** [comment]
Taui has a [Travis configuration](https://github.com/conveyal/taui/blob/dev/.travis.yml) we should be able to use as a starting point.

**Comment by jeancochrane** [comment]
Currently blocked while we wait for AWS credentials.
