### ISSUE TITLE
Don't filter BHA listings by number of bedrooms

### ISSUE THREAD

**Issue by ddohler** [azavea/echo-locator#418]
There's an issue with the BHA listing endpoint where passing the number of bedrooms as a query parameter doesn't work correctly. We don't have a way to resolve the root cause right now, so as a workaround we should omit the bedroom parameter (or send it as null, whichever one is easiest and works). We should continue to filter by max rent, assuming that works correctly.

We should continue to filter Realtor.com listings by the number of bedrooms and max rent.

**Comment by rachelekm** [comment]
If possible, since the query requirements have been subject to change, it may be worth omitting the bedroom parameter completely vs setting to null to hedge against any potential non-null value errors.
