### ISSUE TITLE
Create management command to migrate housing seeker data from S3

### ISSUE THREAD

**Issue by ddohler** [azavea/echo-locator#432]
Create a management command that can migrate data from existing profiles into the Django database.

It should:
- Accept AWS credentials to use (I believe boto will automatically look for authentication credentials in the local environment, so simply using boto may be sufficient).
- Accept an S3 bucket as a parameter
- Read profile data from the target S3 bucket and create corresponding user profiles within the associated Django database.

Notes:
Scripts like this often need to be run multiple times with some user intervention in between to validate data, fix problems, etc., and that can be a struggle if the script's functionality doesn't lend itself to that kind of workflow. Some features that are often helpful in such cases:
  - Recovering from errors, printing a useful identifier so that the offending record can be tracked down later, and continuing to process further records.
  - Doing something intelligent when conflicts are discovered (usually that's either updating the record or skipping it as a duplicate)
  - Accepting a subset of IDs or otherwise enabling filtering on the source dataset so that problematic records can be targeted directly rather than having to re-run the import for the entire set.

You shouldn't necessarily implement all of these features; this is just an example of the kind of thing to be on the lookout for; if you find yourself wanting one of these at least once, then it's probably worth adding it because it'll likely be useful again.

**Comment by aaronxsu** [comment]
#### I. We have two types of files on S3 representing vouchers and user profiles. What are they like?
There are two file naming schemes:
       1. `voucher_number`
       2. `voucher_number-region:uuid`

There can be files that have same `voucher_number` part, but one is just `voucher_number`, the other has the remaining segments. For this situation, we'd want to use information stored in the longer file name since it is supposed to be created at a later time. After verifying, I can confirm the following, as of the time writing this comment:

   - there is only 1 profile as such exists on production; this does not exist on staging
   - for the 1 profile in the production bucket, the version with longer file name indeed has a more recent "last modified at" timestamp.

#### II. Any impact on this script, regarding the above?
Instead of doing such a preflight check the next time before we run the script, we should incorporate this check in the script, and always make sure to read from the file with the most recent "last modified at" timestamp in the above mentioned situation.

#### III. What database tables are we populating? 
In order to successfully migrate these user records into the Postgres DB, I think we should work with 3 tables or models in this task:
   - `User` model, or  `auth_user`  table
   - `UserGroup` model or `auth_user_groups` table
   - `UserProfile` model or `users_userprofile` table
   - `Destination` model or `users_destination` table

#### IV. What fields do we have in the user profile data from S3?
There are 446 user profile objects in the production bucket. But not all objects have the same JSON shape or fields. Note that we are supposed to use the info in these objects to populate all three DB tables mentioned above. 

See the following for the occurrence of keys, please also note that these are just occurrence of the keys, the corresponding value could be null, empty, or no-length:
```
{
  "destinations": 446,
  "favorites": 446,
  "hasVehicle": 446,
  "headOfHousehold": 446,
  "importanceAccessibility": 445,
  "importanceSchools": 445,
  "importanceViolentCrime": 445,
  "key": 446,
  "rooms": 446,
  "useCommuterRail": 445,
  "voucherNumber": 446,
  "clientAccountConfirmed": 138,
  "clientEmail": 138,
  "clientInviteSent": 138
}
```

**Comment by aaronxsu** [comment]
#### V. How should we populate `users_destination`?

```
       Column        |          Type          | Collation | Nullable |                    Default                    
---------------------+------------------------+-----------+----------+-----------------------------------------------
 id                  | bigint                 |           | not null | nextval('users_destination_id_seq'::regclass)
 address             | character varying(200) |           | not null | 
 purpose             | character varying(2)   |           | not null | 
 primary_destination | boolean                |           | not null | 
 profile_id          | bigint                 |           | not null | 
```

`destinations` field in the profile objects from S3 stores an array. The shape of an object in this field is consistent among all profiles, and it looks like the following:
```
    {
      "location": {
        "label": string,
        "position": {
          "lon": number,
          "lat": number
        }
      },
      "primary": boolean,
      "purpose": string
    }
```
I have 2 notes here:
1. Among 446 profiles, 29 have empty `destinations` array. I think this should be fine, as we just don't insert records for them. Sounds good?
2. The DB wants an `address` as a string, but `location.label` in the profile is not the full street address. I think it should depend on how this information is going to be used in the app. Any thoughts?
    - If coordinates are more useful, then we should either add columns to the table, or replace the `address` field by two lat/lon columns.
    - If address is more useful, then we should use a reverse geocoding package to translate that from `location.position.lat` and `location.position.lon`.

**Comment by aaronxsu** [comment]
#### VI. How should we populate `auth_user`?

```
    Column    |           Type           | Nullable |          Default                
--------------+--------------------------+----------+-----------------------------------------
 id           | integer                  | not null | nextval('auth_user_id_seq'::regclass)
 password     | character varying(128)   | not null | 
 last_login   | timestamp with time zone |          | 
 is_superuser | boolean                  | not null | 
 username     | character varying(150)   | not null | 
 first_name   | character varying(150)   | not null | 
 last_name    | character varying(150)   | not null | 
 email        | character varying(254)   | not null | 
 is_staff     | boolean                  | not null | 
 is_active    | boolean                  | not null | 
 date_joined  | timestamp with time zone | not null | 
```

1. `id`: this should be automatic
2. `password`: I think we may generate some random strings for this field, and we will ask users to reset the password. How does it sound?
3. `last_login`: not in the profile directly, but also not a required field, so we may just skip
4. `is_superuser`: false
5. `username`: I am not sure what to do about this. I think we have some choices here. I think we should decide on one of them, then skip and record those that cannot be populated.
    - use the `clientEmail ` from user profile. But see section IV- only 138 profiles have `clientEmail` key
    - use the `headOfHousehold` field from user profile. But even though all profiles have this field, some are empty strings under this key.
6. `first_name` and `last_name`: derive from `headOfHousehold`. If it is empty, skip and record the profile. If not, split by empty space: use the first part as first name; use the remainder as last name, otherwise replicate first name
7. `email`: use the `clientEmail ` from user profile. But see section IV- only 138 profiles have `clientEmail` key. So skip if key does not exist, or the value is empty. Also, it looks like we will need to send users emails to reset their passwords after the migration.I think we may want to have as many email address as possible. But the current user profile objects from S3 only have 138 records with this field, so I think we may want to find out how to make the connection between voucher number and emails.
8. `is_staff`: false
9. `is_active`: true
10. `date_joined`: this info is not stored under any key in the user profile on S3. I think we have the some choices:
    - use the current time when the script is run
    - use the last modification timestamp of the S3 object
    - ask client if they have such info

**Comment by aaronxsu** [comment]
#### VII. How should we populate `auth_user_groups`?

```
  Column  |  Type   | Collation | Nullable |                   Default                    
----------+---------+-----------+----------+----------------------------------------------
 id       | bigint  |           | not null | nextval('auth_user_groups_id_seq'::regclass)
 user_id  | integer |           | not null | 
 group_id | integer |           | not null | 
```

All populated users in `auth_user ` should be in the housing seeker group.

**Comment by aaronxsu** [comment]
#### VIII. How should we populate `users_userprofile`?

```
         Column          |          Type          | Collation | Nullable |                    Default                    
-------------------------+------------------------+-----------+----------+-----------------------------------------------
 id                      | bigint                 |           | not null | nextval('users_userprofile_id_seq'::regclass)
 user_id                 | integer                |           | not null | 
 commute_priority        | character varying(2)   |           | not null | 
 desired_bedrooms        | integer                |           |          | 
 full_name               | character varying(200) |           | not null | 
 has_voucher             | boolean                |           | not null | 
 public_safety_priority  | character varying(2)   |           | not null | 
 rent_budget             | integer                |           |          | 
 school_quality_priority | character varying(2)   |           | not null | 
 travel_mode             | character varying(3)   |           | not null | 
 voucher_bedrooms        | integer                |           |          | 
 voucher_number          | character varying(10)  |           | not null | 
```

1. `commute_priority`: use `importanceAccessibility`, note that this field is required, and there is one profile without this key. The values range from integers 1 to 4. The DB field expects these: https://github.com/azavea/echo-locator/blob/develop/src/backend/users/models.py#L11 . What is the mapping here?
2. `desired_bedrooms`: not sure if this is `rooms` in the profile object or not.
3. `full_name`: I think `headOfHousehold`- all objects have this field, but the value can be empty.
4. `has_voucher`: I think as long as there is a `voucherNumber` field in the object and the value is not empty, this should be `true`
5. `public_safety_priority`: use `importanceViolentCrime`, the situation is the same as point 1 above.
6. `rent_budget`: not exist in the profile object keys, and this field is optional in the DB
7. `school_quality_priority`: use `importanceSchools`, the situation is the same as point 1 above.
8. `travel_mode`: there are `hasVehicle` and `useCommuterRail` in the user profile object, both are boolean fields. DB expects one of the following: https://github.com/azavea/echo-locator/blob/develop/src/backend/users/models.py#L6 . Any suggestions?
9. `voucher_bedrooms`: not sure if this is `rooms` in the profile object or not.
10. `voucher_number`: use `voucherNumber`

**Comment by aaronxsu** [comment]
@ddohler I spent some time today to go over some details in terms of the DB schema and the keys/fields available in those profile objects on S3. I wrote down some findings, thoughts, and questions in the above comments. 

When you get a chance, please let me know what you think, as I think this is another issue that potentially has some downstream impact for the migration. I am also happy to have a meeting to walk this through together.

**Comment by ddohler** [comment]
Thanks a ton for writing this up in so much detail, @aaronxsu ! Here are my thoughts on the questions you raised:

> Among 446 profiles, 29 have empty destinations array. I think this should be fine, as we just don't insert records for them. Sounds good?

Do any of those 29 have `clientEmail` set? I think if there is a `clientEmail` we should attempt to save as much data as we can, but if there isn't and they're also missing the destinations then I agree it's fine to just drop them.

> The DB wants an address as a string, but location.label in the profile is not the full street address. I think it should depend on how this information is going to be used in the app. Any thoughts? 

I didn't realize the location.label wasn't the full address! As you suggest, the lat/lon is the most important field, so let's update the DB schema to match this and add a `PointField()` to the `Destination` model. It'll get geocoded on the frontend before saving, so that should match what the app expects.

> `password`: I think we may generate some random strings for this field, and we will ask users to reset the password. How does it sound?

We actually won't be using this field at all since we're using passwordless authentication. I would still set it to a random string just for safety's sake, but we won't have to ask anyone to reset it.

> `username`: I am not sure what to do about this. I think we have some choices here. I think we should decide on one of them, then skip and record those that cannot be populated.
>    use the clientEmail from user profile. But see section IV- only 138 profiles have clientEmail key

I don't think we have any other option besides using the `clientEmail` field because we assume that all clients have email addresses. But that's okay, I think, because I'm pretty sure that if `clientEmail` is blank, it means that the user has never logged into the app themselves, so they don't really have an account anyway. I think it would be good to list the voucher numbers for which we weren't able to create an account -- BHA might want to know that information.

> `date_joined`: this info is not stored under any key in the user profile on S3. I think we have the some choices:
>
>   - use the current time when the script is run
>   - use the last modification timestamp of the S3 object
>   - ask client if they have such info

I think using the S3 timestamp is probably the best tradeoff between correctness and effort; this isn't a particularly important field, but the S3 timestamp should be pretty close to the correct answer and it's easy to use, so let's do that.

> `commute_priority`: use importanceAccessibility, note that this field is required, and there is one profile without this key. The values range from integers 1 to 4. The DB field expects these: https://github.com/azavea/echo-locator/blob/develop/src/backend/users/models.py#L11 . What is the mapping here?

The mapping is 1 = Not Important up to 4 = Very Important: https://github.com/azavea/echo-locator/blob/develop/taui/src/locales/en/translations.js#L203-L208

> `travel_mode`: there are `hasVehicle` and `useCommuterRail` in the user profile object, both are boolean fields. DB expects one of the following: https://github.com/azavea/echo-locator/blob/develop/src/backend/users/models.py#L6 . Any suggestions?

Here's the mapping:
- `hasVehicle = true` -> `CAR`.
- `useCommuterRail = true` -> `BUS_TRAIN_EXPRESS`
- Otherwise -> `BUS_TRAIN`

But I wonder if we might have to adjust the Django fields to make this match better--are there any instances where both `hasVehicle` and `useCommuterRail` are true?

> `voucher_bedrooms`: not sure if this is `rooms` in the profile object or not.
> `desired_bedrooms`: not sure if this is `rooms` in the profile object or not.

`desired_bedrooms` should be blank, and `voucher_bedrooms` should be populated with the value of `rooms` in the profile. We didn't allow users without vouchers to use the application previously, so there won't be any users who don't have vouchers.

I hope that helps, please let me know if I didn't answer something or if any of those answers are unclear!

**Comment by aaronxsu** [comment]
@ddohler thanks so much for the detailed responses to the questions raised. They make sense to me. I think I am good to go for the implementation. I will let you know if newer questions or concerns come up along the way.

**Comment by aaronxsu** [comment]
>But I wonder if we might have to adjust the Django fields to make this match better--are there any instances where both hasVehicle and useCommuterRail are true?

@ddohler I looked into the data again, and here is the finding:

Among 128 accounts with non-empty `clientEmail` field:
```
{'both_true': 0, 'only_hasVehicle_true': 31, 'only_useCommuterRail_true': 90, 'both_false': 7}
```

So I think assuming the suggested mapping mentioned in your comment should be fine. What do you think?

**Comment by ddohler** [comment]
Yep, I think that's right! I checked on staging, and if you select "Car" as the mode, it'll clear the "Commuter rail" checkbox after you save, so that implies that the existing code is treating these as exclusive choices.
