### ISSUE TITLE
Move from SES sandbox

### ISSUE THREAD

**Issue by rachelekm** [azavea/echo-locator#460]
In order to send emails through Amazon SES to non-verified email addresses (e.g. not @stg.echosearch.org addresses or the ses simulator) we need to submit a support request to remove us from the SES sandbox: https://docs.aws.amazon.com/ses/latest/dg/request-production-access.html

**Comment by rachelekm** [comment]
@ddohler would you be able to confirm these are the correct responses for opening a support request with AWS to take us out of the SES sandbox. Since we're expecting a curated list of emails it seemed worth keeping the use case description brief and simple, though I'm not sure if we have a plan for bounces that should be outlined here.

Note: This is just for staging and we'll need to submit a similar support request for production.

1. Marketing or Transactional:
  **Answer: Transactional**

2. Website URL:
  **Answer: https://stg.echosearch.org/**

3. Use case description, explain how you plan to use Amazon SES to send email:
  **Answer: Sending login links for users opting to create an account as well as sending password reset links**

4. Additional contacts:
  **Answer: systems+bha@azavea**

5. Preferred contact language
  **Answer: English**

**Comment by ddohler** [comment]
👍 I'd update the use-case text to note that this is a staging/client testing environment, but otherwise that looks good!

**Comment by rachelekm** [comment]
Great, thanks! I updated the use-case to clarify this is for a staging/client testing env and submitted the request. ~~I'll update this comment and close if/when the request has been approved.~~ **Update:** Request has been approved, we are out the sandbox.
