### ISSUE TITLE
Make edits to Spanish translations

### ISSUE THREAD

**Issue by stephwall** [azavea/echo-locator#467]
**Update!** Please use this revised document, which was sent in response to questions about inconsistencies between requested changes and translations on the site. https://docs.google.com/document/d/1HR5IGwh3GR4I9n_mUOyYxaSr9TRohHld/edit?usp=sharing&ouid=103386654251334027210&rtpof=true&sd=true

**Comment by ddohler** [comment]
This should branch off of, and be merged into, the `release/2022-03-02` branch.
