### ISSUE TITLE
Investigate mysterious redirects when accessing ObtainToken view from port 9966

### ISSUE THREAD

**Issue by ktohalloran** [azavea/echo-locator#488]
_Originally posted by @ddohler in https://github.com/azavea/echo-locator/pull/482#discussion_r866286564_

Something very strange is going on when trying to hit the `ObtainToken` endpoint via port `9966`.

Here are the logs I get when I access this via `curl`:
```
django_1    | [2022-05-05 20:45:36 +0000] [7] [DEBUG] GET /api/auth/login/
django_1    | 172.28.0.3 - - [05/May/2022:20:45:36 +0000] "GET /api/auth/login/?echo_auth=AAAAAwRoTvOSkbCDhf8E9VyW HTTP/1.1" 302 0 "-" "curl/7.82.0" <-- Successfully returns a 302
django_1    | [2022-05-05 20:45:36 +0000] [7] [DEBUG] GET /
django_1    | 172.28.0.3 - - [05/May/2022:20:45:36 +0000] "GET / HTTP/1.1" 200 0 "http://django:8085/api/auth/login/?echo_auth=AAAAAwRoTvOSkbCDhf8E9VyW" "curl/7.82.0"
```

And here's what curl sees:
```
$ curl -v http://localhost:9966/api/auth/login/?echo_auth=AAAAAwRoTvOSkbCDhf8E9VyW
*   Trying 127.0.0.1:9966...
* Connected to localhost (127.0.0.1) port 9966 (#0)
> GET /api/auth/login/?echo_auth=AAAAAwRoTvOSkbCDhf8E9VyW HTTP/1.1
> Host: localhost:9966
> User-Agent: curl/7.82.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Access-Control-Allow-Headers: Cache-Control, Pragma, Origin, Authorization, Content-Type, X-Requested-With
< Access-Control-Allow-Methods: GET, PUT, POST
< access-control-allow-origin: *
< server: gunicorn
< date: Thu, 05 May 2022 20:49:47 GMT
< connection: close
< content-type: text/html; charset="utf-8"
< cache-control: max-age=0, public
< last-modified: Fri, 29 Apr 2022 18:35:02 GMT
< etag: "626c2fd6-2c8"
< content-length: 712
< x-content-type-options: nosniff
< referrer-policy: same-origin
< 
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=0">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/normalize/8.0.0/normalize.min.css" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
    <link href="https://api.mapbox.com/mapbox.js/v3.1.1/mapbox.css" rel="stylesheet">
    <link rel="shortcut icon" href="https://www.bostonhousing.org/favicon.ico" type="image/x-icon">
  </head>
  <body>
    <div id="root" class="app-root"></div>
    <script src="assets/index.js"></script>
  </body>
</html>
* Closing connection 0
```

That looks like Django received at least 3 requests for what should have been only one, and _something_ spookily followed the redirect without ever letting `curl` see it (`curl` doesn't follow redirects via default, so if the redirect had been returned to `curl` it would have just quit at that point).

My best guess for what that spooky something might be is mastarm. When we access Django via port `9966` we're getting routed through mastarm's proxy feature, and the proxy misbehaving could certainly explain Django seeing mysterious requests that don't seem to come from anywhere 👻 . What it looks like may be happening is that the "inside" of the mastarm proxy is following the redirect _on its own_, rather than passing it back to the client that made the initial request.

**Comment by ktohalloran** [comment]
This seems to have resolved itself with the merge of [PR 457](https://github.com/azavea/echo-locator/pull/457) and logging in can now occur completely through **localhost:9966**. @ddohler am I good to close this issue?

**Comment by ddohler** [comment]
Wonderful news! Yup, let's close it!
