### ISSUE TITLE
Provision production environment

### ISSUE THREAD

**Issue by jeancochrane** [azavea/echo-locator#5]
Set up the production environment, including:

* Stand up production version of Terraform resources for the frontend bundle (S3/CloudFront)
* Configure Mastarm deployments in CI for production
* Provision DNS and certificates

Note that Amplify resources should all be taken care of in #39.

**Comment by jeancochrane** [comment]
Currently blocked while we wait for AWS credentials.

**Comment by hectcastro** [comment]
@flibbertigibbet Do you know what the target domain is for the site? If not, do you know that we've started to talk to the client about it?
