### ISSUE TITLE
Phase II Deployment

### ISSUE THREAD

**Issue by aaronxsu** [azavea/echo-locator#502]
The production application should be deployed to app.echosearch.org

Below is a list of known one-off items that need to be done in order to complete the deployment.

- [x] One task we are now sure to be on the to-do list is to plan and implement the handling of env vars for the frontend for production deployment, as discussed in here: https://github.com/azavea/echo-locator/pull/500#discussion_r872656289
- [x] Importing Users
   1. Add AmazonS3ReadOnlyAccess to ecsecho*TaskRole
   2. Enter container via `aws ecs execute-command`
   3. Run ./manage.py loaddata users/fixtures/group_permissions from (should this be done elsewhere?)
   4. `./manage.py migrate_housing_seeker_data -b <bucket-name> -p public`
- [x] Add `default_from_email` and `aws_s3_photo_bucket` variables to `terraform.tfvars` in S3, like we have for staging
- [x] Import neighborhoods
  1. Locally, run `./update_data.sh` in `neighborhood_data` directory, then run `./scripts/imagepublish production` to push the neighborhood images to production assets bucket
  2. Run `./manage.py import_neighborhood_data s3://echolocator-production-data-us-east-1/neighborhoods.json s3://echolocator-production-data-us-east-1/neighborhood_bounds.json s3://echo-locator-production-site-us-east-1/assets/neighborhoods/` via `execute-command` as with the user import.
- [x] Complete the SES setup as described in #491
- [x] Send BHA links for the Login and Signup buttons on https://echosearch.org/

Note that this task can be started before #563 is done, but can't be finished until #563 is because it needs to include the update data

**Comment by ddohler** [comment]
Still waiting on client feedback; we may need to swap this out if there are critical issues that are discovered.
