### ISSUE TITLE
Profile import swaps lat/lon for points

### ISSUE THREAD

**Issue by ddohler** [azavea/echo-locator#510]
It looks like the latitude / longitude values are getting swapped for locations imported from S3 profiles:

<img width="1115" alt="Screen Shot 2022-05-18 at 10 59 34" src="https://user-images.githubusercontent.com/447977/169079846-b4435ee6-e431-47a4-8a99-cf33ba43c3ca.png">

**Comment by ddohler** [comment]
Hey @lukemckinstry I’m using ZenHub in GitHub, [click this link](https://app.zenhub.com/workspaces/geospatial-apps-5cd1c36cfad74779f9c9cb2e/board) to join my workspace and see other features available in GitHub or [download the ZenHub extension](https://www.zenhub.com/extension) and sign up with your GitHub account. 
  _Posted using [ZenHub](https://www.zenhub.com)_

**Comment by lukemckinstry** [comment]
After discussion we determined the scope of this issue to be altering the management script `migrate_housing_seeker_data` to correct for the mix up between the `lat` and `lon` fields by swapping them. The `user profile` data on staging will need to be removed and then the migration should be performed again with the corrected script.
