### ISSUE TITLE
Add Favorites support to User Profile

### ISSUE THREAD

**Issue by ddohler** [azavea/echo-locator#515]
1. The UserProfile model should have a `favorites` field which should be an [array of strings](https://docs.djangoproject.com/en/4.0/ref/contrib/postgres/fields/#arrayfield) (it should default to empty: `list`). The values stored will be zip codes.
2. The user import script should populate this field when loading profiles
3. The API should include this field in GET requests and accept it on POST / PUT requests
4. The frontend should use this field to filter the `Saved` section of the dock (it already has logic to do this, so this is just making sure it uses the right field)
<img width="417" alt="Screen Shot 2022-05-19 at 13 41 26" src="https://user-images.githubusercontent.com/447977/169363806-00b62305-1170-4195-a3c7-2c4fd9ff9e4a.png">
5. Clicking the star next to a neighborhood should trigger an API request to save the favorite to the user's profile.

**Comment by rachelekm** [comment]
Two conditional checks for `props.userProfile.favorites` were added to the `NeighborhoodDetails` component in PR #514 to allow the app to function until Favorites exists. [Those changes in neighborhood-detail.js](https://github.com/azavea/echo-locator/pull/514/commits/ce9db13952aaf0e7f90cfb7a3fbc68e034052056#diff-91a82fb12457b83b12ee2841000427dfa735d41a407aec1e29a124053ca426f9) will be unnecessary once this is complete and can be reverted.
