### ISSUE TITLE
Map sometimes loads with corrupted polygons

### ISSUE THREAD

**Issue by ddohler** [azavea/echo-locator#552]
This happens for me on Firefox, but not always. It seems most likely to happen on initial login. The intermittent nature makes me suspect that it's a race condition.
<img width="1075" alt="172646662-c7144477-75cc-4a30-80b4-91bb0e59c2d2" src="https://user-images.githubusercontent.com/447977/172913360-e12710f7-87aa-42a3-9607-c6963312d572.png">

**Comment by ktohalloran** [comment]
Addressed via issue #574 and PR #576.
