### ISSUE TITLE
Layout issues

### ISSUE THREAD

**Issue by lederer** [azavea/echo-locator#63]
Per https://github.com/azavea/echo-locator/pull/62

- [ ] the login form is not centered, but scrolled halfway off the page on Chrome/Linux
- [x] the header now scrolls with the page (unsure if intentional, particularly on the map page)
- [x] sidebar on map page no longer full height
- [ ] the search and login pages scroll, but the scrollbar is not visible

**Comment by lederer** [comment]
A couple of these items remain unaddressed but aren't critical.

**Comment by flibbertigibbet** [comment]
Is the lack of scrollbars not a usability issue?

**Comment by lederer** [comment]
It is, but both the search and login pages imply scrollability if their content overflows the viewport, hence not critical. 

Scrollbars do appear Edge/Win and FF/Win
but not Chrome/Win, Chrome/Mac, Safari/Mac.

I troubleshot for awhile but moved on, given the above observations and budget constraints.
