### ISSUE TITLE
Render map markers for all sidebar neighborhoods

### ISSUE THREAD

**Issue by lederer** [azavea/echo-locator#97]
Currently on the map we show a marker for the featured destination (eg, work), a marker for the active neighborhood, and, iff transit, the route between them.

We should also show markers for the other (up to two) neighborhoods currently in the sidebar. They will have no icon and be colored `$brand-blue` `#15369d`

**Comment by flibbertigibbet** [comment]
Should clicking on the marker also go to details and show route (same as the underlying neighborhood markers)?

**Comment by lederer** [comment]
Good question. Yes it should.
